[libraries.lib_rtl]
files = ["src/rtl/vhdl/**/*.vhd"]

[libraries.vunit_lib]
files = [".venv/lib/python*/site-packages/vunit/vhdl/**/*.vhd"]

vunit_list.is_third_party = true

[libraries.lib_bench]
files = ["src/bench/vunit/**/*.vhd"]
