name: Regression Tests

on: [push, pull_request]

jobs:
  build:
    name: Python ${{matrix.python-version}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Verilator
        run: |
          current_date=$(date +'%Y-%m-%d')
          wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/${current_date}/oss-cad-suite-linux-x64-${current_date//-/}.tgz --progress=dot:mega
          tar -xvf oss-cad-suite-linux-x64-${current_date//-/}.tgz
          rm oss-cad-suite-linux-x64-${current_date//-/}.tgz

      - name: Install Lcov
        run: |
          sudo apt-get install lcov

      - name: Install NVC
        run: |
          UBUNTU_VERSION=$(lsb_release -rs)
          LATEST_NVC=$(curl -s https://api.github.com/repos/nickg/nvc/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')
          echo "Installing latest NVC version: $LATEST_NVC for Ubuntu $UBUNTU_VERSION"
          LATEST_NVC_DEB=$(curl -s https://api.github.com/repos/nickg/nvc/releases/latest | grep -Po '"browser_download_url": "\K.*?\.deb(?=")' | grep "ubuntu-${UBUNTU_VERSION}")
          wget "$LATEST_NVC_DEB"
          sudo dpkg -i "$(basename "$LATEST_NVC_DEB")"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Lint code with ruff
        run: |
          echo "Running Python Code Checks"
          ruff check --config pyproject.toml

      - name: Test with pytest
        run: |
          echo "Running Python Tests"
          source oss-cad-suite/environment
          pytest
